version: "3"

services:
    mysql:
        image: mysql:8.3.0
        container_name: mysql-pixelwar
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pixelwar
        ports:
            - "0.0.0.0:3336:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
    redis:
        image: redis:7.2.4
        container_name: redis-pixelwar
        restart: always
        ports:
            - "0.0.0.0:3337:6379"
        volumes:
            - ./data/redis:/data
