version: "3"

services:
    proxy:
        image: nginx:alpine
        network_mode: "host"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./logs:/var/log/nginx
            - ../frontend/dist:/var/www/html
