on:
    pull_request:
        branches:
            - master
            - main
            - dev
            - features/*
            - feature/*
            - fix/*

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"
            - name: Install dependencies (Backend)
              run: cd ./backend && npm install
            - name: Lint (Backend)
              run: cd ./backend && npm run lint
            - name: Install dependencies (Frontend)
              run: cd ./frontend && npm install
            - name: Lint (Frontend)
              run: cd ./frontend && npm run lint
